model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

[mcp_servers.testsprite]
command = "npx.cmd"
args = ["-y", "@testsprite/testsprite-mcp@latest"]
env = { API_KEY = "sk-user-8GDkgZTu29XyzJhsDfYWp7Iy1N8ev-b2y8LuoPXnu4F6gMChNSZr1Z3gpsIWokED6LgLe6MmXxexV5q7ym9T0Hkd3y_Ub-egUSR1Niai79Q5R5QOHwrlRoXz8nwfdEtb70I" }
startup_timeout_sec = 120